version: '3.8'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.0-alpine
    volumes:
      - db_auth_vol:/var/lib/postgresql/data
volumes:
  db_auth_vol: {}
