name: auth
description: Auth Service.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  conduit: ^4.4.0
  conduit_core: ^4.4.0
  conduit_postgresql: ^4.4.0
  jaguar_jwt: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
